/**
 * One-time local ClickHouse provisioning (admin lane). Creates databases scopewatch / scopewatch_replay /
 * scopewatch_contract with schema and per-namespace least-privilege users, and writes NON-SECRET usernames plus
 * generated local-dev passwords to runtime/clickhouse-local.env (gitignored).
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync, chmodSync } from 'node:fs';
import { adminClient, provisionNamespace, randomPassword } from '../src/integrations/clickhouse/admin.js';
import { parseEnvFile } from '../src/server/services/envfile.js';

const URL_ = process.env['CLICKHOUSE_URL'] ?? 'http://127.0.0.1:18123';
const ADMIN_USER = process.env['SCOPEWATCH_CH_ADMIN_USER'] ?? 'sw_admin';
const ADMIN_PW = process.env['SCOPEWATCH_CH_ADMIN_PASSWORD'] ?? 'local-dev-admin';
const OUT = 'runtime/clickhouse-local.env';

const NAMESPACES = [
  { prefix: 'CLICKHOUSE', db: 'scopewatch', ingest: 'sw_native_ingest', query: 'sw_native_query' },
  { prefix: 'CLICKHOUSE_REPLAY', db: 'scopewatch_replay', ingest: 'sw_replay_ingest', query: 'sw_replay_query' },
  { prefix: 'CLICKHOUSE_CONTRACT', db: 'scopewatch_contract', ingest: 'sw_contract_ingest', query: 'sw_contract_query' },
];

async function main(): Promise<void> {
  const existing = existsSync(OUT) ? parseEnvFile(readFileSync(OUT, 'utf8')) : {};
  const admin = adminClient(URL_, ADMIN_USER, ADMIN_PW);
  try {
    const v = await (await admin.query({ query: 'SELECT version() AS v', format: 'JSONEachRow' })).json<{ v: string }>();
    console.log(`ClickHouse ${v[0]?.v} at ${URL_}`);
    const lines = [`# generated by tools/ch-setup.ts; local development only; gitignored`, `CLICKHOUSE_URL=${URL_}`];
    for (const ns of NAMESPACES) {
      const users = {
        ingest: { username: ns.ingest, password: existing[`${ns.prefix}_INGEST_PASSWORD`] ?? randomPassword() },
        query: { username: ns.query, password: existing[`${ns.prefix}_QUERY_PASSWORD`] ?? randomPassword() },
      };
      const r = await provisionNamespace(admin, ns.db, users);
      console.log(`provisioned ${ns.db}: users ${ns.ingest} (INSERT,SELECT) ${ns.query} (SELECT); query_log grant: ${r.queryLogGrant}`);
      const dbVar = ns.prefix === 'CLICKHOUSE' ? 'CLICKHOUSE_DATABASE' : `${ns.prefix}_DATABASE`;
      lines.push(`${dbVar}=${ns.db}`, `${ns.prefix}_INGEST_USERNAME=${users.ingest.username}`, `${ns.prefix}_INGEST_PASSWORD=${users.ingest.password}`, `${ns.prefix}_QUERY_USERNAME=${users.query.username}`, `${ns.prefix}_QUERY_PASSWORD=${users.query.password}`);
    }
    mkdirSync('runtime', { recursive: true });
    writeFileSync(OUT, lines.join('\n') + '\n', { mode: 0o600 });
    chmodSync(OUT, 0o600);
    console.log(`wrote ${OUT} (local dev credentials; gitignored)`);
  } finally {
    await admin.close();
  }
}

main().catch((e) => {
  console.error(`ch-setup failed: ${(e as Error).message}`);
  process.exit(1);
});
